### ISSUE TITLE
The effect is not good

### ISSUE THREAD

**Issue by lofyol** [Auggen21/Low-Light-Image-Enhacement-1#1]
Thank you very much for your repetition, but I ran the result, which is not as good as the original author's encryption code. What's the problem?

**Comment by koshygeoji** [comment]
I have checked it, actually its a small datatype problem. i have used the uint8 format for processing. Change that convert to double or im2double and will get the result as that of author..

**Comment by koshygeoji** [comment]
Yes, the result is not good as said in paper.. The spreading effect in result is due to the selection of pyramid level as 6. I have updated the code for better result with less pyramid level. 
You can verify that all the said procedures in the paper are followed as such, but the result is not accurate to the journal is up-to with the author of the paper. And i am not the author, i try to recreate their work for my research purpose.

**Comment by koshygeoji** [comment]
Here is the link of another depository which implemented low light with better result.. You can check for that.
https://github.com/Auggen21/low-light-image-enhancement2
